import { writable, derived } from 'svelte/store'

// Types
type TranslationDictionary = {
  [key: string]: string
}

type Languages = {
  [key: string]: TranslationDictionary
}

// Default language
const DEFAULT_LANGUAGE = 'en'

// Translation dictionaries
const translations: Languages = {
  en: {
    'version-value': '1.2.0',
    'send-webhook': 'Send Discord Webhook',
    'webhook-url': 'Webhook URL',
    name: 'Name',
    avatar: 'Avatar URL',
    message: 'Message',
    send: 'Send',
    bot: 'Bot',
    'message-placeholder': 'Enter your message here',
    token: 'Token',
    login: 'Login',
    logout: 'Logout',
    invite: 'Invite',
    status: 'Status',
    activity: 'Activity',
    'status-details': 'Status Details',
    'status-details-placeholder': 'Enter your status details here',
    'twitch-url': 'Twitch.tv URL',
    'update-status': 'Update Status',
    settings: 'Settings',
    theme: 'Theme',
    'show-token': 'Show Token',
    language: 'Language',
    about: 'About',
    'bot-state': 'Bot State',
    value: 'Value',
    'run-code': 'Run Code',
    'run-code-placeholder': 'Enter JavaScript code here...',
    output: 'Output',
    run: 'Run',
    stats: 'Stats',
    users: 'Users',
    'messages-sent': 'Messages Sent',
    'messages-received': 'Messages Received',
    'on-join': 'On Join',
    'on-leave': 'On Leave',
    'on-ban': 'On Ban',
    'private-messages-received': 'Private Messages Received',
    servers: 'Servers',
    commands: 'Commands',
    'time-spent-in-app': 'Time Spent in App',
    'webhooks-sent': 'Webhooks Sent',
    cancel: 'Cancel',
    'add-command': 'Add Command',
    'no-commands-found': 'No commands found.',
    'command-exported-to-clipboard': 'Command exported to clipboard!',
    delete: 'Delete',
    'are-you-sure-you-want-to-delete-the-command': 'Are you sure you want to delete the command?',
    'open-quote': '“',
    'close-quote': '”',
    'edit-command': 'Edit Command',
    'choose-command-type': 'Choose Command Type',
    'message-received': 'Message Received',
    'private-message-received': 'Private Message Received',
    'member-join': 'Member Join',
    'member-leave': 'Member Leave',
    'member-ban': 'Member Ban',
    reaction: 'Reaction',
    command: 'Command',
    description: 'Description',
    'reaction-placeholder': 'Emoji ID or name or 😊',
    'specific-message-only': 'Specific Message Only',
    'message-id': 'Message ID',
    phrase: 'Phrase',
    'requires-role': 'Requires Role',
    'required-role': 'Required Role',
    'role-id': 'Role ID',
    'requires-admin': 'Requires Admin',
    'send-message': 'Send Message',
    'channel-message': 'Channel Message',
    'send-channel-embed': 'Send Channel Embed',
    'channel-embed-title': 'Channel Embed Title',
    'channel-embed-description': 'Channel Embed Description',
    'channel-embed-footer': 'Channel Embed Footer',
    'channel-embed-image': 'Channel Embed Image',
    'channel-embed-thumbnail': 'Channel Embed Thumbnail',
    'channel-embed-color': 'Channel Embed Color',
    'is-specific-channel': 'Is Specific Channel',
    'specific-channel': 'Specific Channel',
    'send-private-message': 'Send Private Message',
    'private-message': 'Private Message',
    'send-private-embed': 'Send Private Embed',
    'private-embed-title': 'Private Embed Title',
    'private-embed-description': 'Private Embed Description',
    'private-embed-footer': 'Private Embed Footer',
    'private-embed-image': 'Private Embed Image',
    'private-embed-thumbnail': 'Private Embed Thumbnail',
    'private-embed-color': 'Private Embed Color',
    'react-to-message': 'React To Message',
    'ignore-error-message': 'Ignore Error Message',
    'delete-if-contains': 'Delete If Contains',
    'delete-if-strings': 'Delete If Strings',
    'delete-after': 'Delete After',
    'delete-x-times': 'Delete X Times',
    'delete-num': 'Delete Num',
    'is-nsfw': 'Is NSFW',
    moderation: 'Moderation',
    kick: 'Kick',
    ban: 'Ban',
    'voice-mute': 'Voice Mute',
    'role-assigner': 'Role Assign',
    'role-to-assign': 'Role To Assign',
    'update-command': 'Update Command',
    action: 'Action',
    hours: 'h',
    minutes: 'm',
    seconds: 's',
    'status-online': 'Online',
    'status-idle': 'Idle',
    'status-dnd': 'Do Not Disturb',
    'status-invisible': 'Invisible',
    'activity-playing': 'Playing',
    'activity-streaming': 'Streaming',
    'activity-listening': 'Listening',
    'activity-watching': 'Watching',
    'activity-none': 'None',
    'activity-competing': 'Competing',
    'language-tooltip': 'The language may be machine translated.',
    'no-state-data': 'No state data found.',
    help: 'Help',
    details: 'Details',
    actions: 'Actions',
    'command-trigger': 'Command Trigger',
    'command-only': 'Command Only',
    'starts-with': 'Starts With',
    'startup-js': 'Startup JavaScript',
    save: 'Save',
    'restart-js-engine': 'Restart JS Engine',
    export: 'Export',
    import: 'Import',
    general: 'General',
    openai: 'OpenAI',
    'openai-api-key': 'OpenAI API Key',
    'enter-your-openai-api-key': 'Enter your OpenAI API key...',
    'openai-model': 'OpenAI Model',
    'developer-prompt': 'Developer Prompt',
    'enter-your-custom-developer-prompt': 'Enter your custom developer prompt...',
    advanced: 'Advanced',
    'use-legacy-interpreter': 'Use Legacy Interpreter',
    // AI Chat strings
    'ai-assistant': 'AI Assistant',
    'ai-chat-started': 'AI assistant ready to help edit command:',
    'proposed-changes': 'Proposed Changes',
    changes: 'changes',
    'accept-changes': 'Accept Changes',
    reject: 'Reject',
    'changes-applied': 'Changes applied successfully',
    'changes-rejected': 'Changes rejected',
    'describe-changes': 'Describe what you want to change...',
    'api-key-needed': 'OpenAI API key required',
    'openai-key-required': 'Please add your OpenAI API key in Settings to use the AI assistant.',
    'select-model': 'Select AI Model',
    'total-tokens': 'Total tokens used',
    'new-chat': 'New Chat',
    close: 'Close',
    'make-funnier': 'Make funnier',
    'add-randomness': 'Add randomness',
    'use-mentions': 'Use mentions',
    'add-counter': 'Add counter',
    'quick-make-funnier': 'Make this command response funnier and more engaging',
    'quick-add-random': 'Add random variations to the response using $random{}',
    'quick-add-mentions': 'Include user mentions like $name and $botName in the response',
    'quick-add-counter': 'Add a counter using $eval and botState to track command usage',
    // Interaction Commands
    interactions: 'Interactions',
    'add-interaction': 'Add Interaction',
    'edit-interaction': 'Edit Interaction',
    'no-interactions-found': 'No interactions found.',
    'sync-all': 'Sync All',
    registered: 'Registered',
    'not-registered': 'Not Registered',
    register: 'Register',
    unregister: 'Unregister',
    options: 'Options',
    buttons: 'Buttons',
    edit: 'Edit',
    'confirm-delete': 'Confirm Delete',
    'delete-interaction-confirm': 'Are you sure you want to delete interaction',
    'command-details': 'Command Details',
    'command-name': 'Command Name',
    'command-name-hint': 'Lowercase, no spaces. Use letters, numbers, hyphens, underscores.',
    'command-description': 'Command Description',
    'command-options': 'Command Options',
    'add-option': 'Add Option',
    'no-options-hint': 'No options. Add options to let users provide input to your command.',
    'option-name': 'Option Name',
    'option-type': 'Option Type',
    'option-required': 'Required',
    required: 'Required',
    'option-description': 'Option Description',
    'root-action': 'Command Response',
    'root-action-hint': 'What happens when the slash command is used.',
    'add-button': 'Add Button',
    'no-buttons-hint': 'No buttons. Add buttons to create interactive responses.',
    'max-buttons-warning': 'Maximum 5 buttons per row. Discord limits buttons to 5 per action row.',
    'response-buttons': 'Response Buttons',
    'no-response-buttons-hint': 'Add buttons to attach to this response.',
    'nesting-level': 'Level',
    'button-label': 'Button Label',
    'button-style': 'Button Style',
    'button-custom-id': 'Custom ID',
    'button-emoji': 'Emoji',
    'button-url': 'URL',
    'button-disabled': 'Disabled',
    'button-action': 'Button Action',
    'style-primary': 'Primary',
    'style-secondary': 'Secondary',
    'style-success': 'Success',
    'style-danger': 'Danger',
    'style-link': 'Link',
    ephemeral: 'Ephemeral (only visible to user)',
    'defer-reply': 'Defer Reply (for slow actions)',
    'add-action': 'Add Action',
    'all-actions-added': 'All actions added',
    'interaction-send-channel-message': 'Send Channel Message',
    'interaction-send-channel-embed': 'Send Channel Embed',
    'embed-title': 'Title',
    'embed-description': 'Description',
    'embed-color': 'Color (hex)',
    'embed-image': 'Image URL',
    'embed-thumbnail': 'Thumbnail URL',
    'embed-footer': 'Footer',
    disabled: 'Disabled',
    search: 'Search',
    // Validation messages
    'fix-errors-to-save': 'Fix errors to save',
    'description-required': 'Description is required',
    'command-required': 'Command is required',
    'message-is-required': 'Message is required',
    'embed-field-required': 'At least one embed field is required',
    'channel-id-required': 'Channel ID is required',
    'reaction-required': 'Reaction is required',
    'delete-strings-required': 'Delete strings are required',
    'delete-number-required': 'Delete number must be at least 1',
    'role-id-is-required': 'Role ID is required',
    'no-actions-added-hint': 'No actions added. Add at least one action.',
    'send-channel-message': 'Send Channel Message'
  },
  es: {
    'send-webhook': 'Enviar Webhook de Discord',
    'webhook-url': 'URL del Webhook',
    name: 'Nombre',
    avatar: 'URL del Avatar',
    message: 'Mensaje',
    send: 'Enviar',
    bot: 'Bot',
    'message-placeholder': 'Escribe tu mensaje aquí',
    token: 'Token',
    login: 'Iniciar sesión',
    logout: 'Cerrar sesión',
    invite: 'Invitar',
    status: 'Estado',
    activity: 'Actividad',
    'status-details': 'Detalles del estado',
    'status-details-placeholder': 'Escribe los detalles de tu estado aquí',
    'twitch-url': 'URL de Twitch.tv',
    'update-status': 'Actualizar estado',
    settings: 'Configuración',
    theme: 'Tema',
    'show-token': 'Mostrar token',
    language: 'Idioma',
    about: 'Acerca de',
    'bot-state': 'Estado del bot',
    value: 'Valor',
    'run-code': 'Ejecutar código',
    'run-code-placeholder': 'Escribe el código JavaScript aquí...',
    output: 'Salida',
    run: 'Ejecutar',
    stats: 'Estadísticas',
    users: 'Usuarios',
    'messages-sent': 'Mensajes enviados',
    'messages-received': 'Mensajes recibidos',
    'on-join': 'En unirse',
    'on-leave': 'En abandonar',
    'on-ban': 'En banear',
    'private-messages-received': 'Mensajes privados recibidos',
    servers: 'Servidores',
    commands: 'Comandos',
    'time-spent-in-app': 'Tiempo en la aplicación',
    'webhooks-sent': 'Webhooks enviados',
    cancel: 'Cancelar',
    'add-command': 'Añadir comando',
    'no-commands-found': 'No se encontraron comandos.',
    'command-exported-to-clipboard': '¡Comando exportado al portapapeles!',
    delete: 'Eliminar',
    'are-you-sure-you-want-to-delete-the-command':
      '¿Estás seguro de que quieres eliminar el comando?',
    'open-quote': '“',
    'close-quote': '”',
    'edit-command': 'Editar comando',
    'choose-command-type': 'Escoge el tipo de comando',
    'message-received': 'Mensaje recibido',
    'private-message-received': 'Mensaje privado recibido',
    'member-join': 'Miembro se unió',
    'member-leave': 'Miembro abandonó',
    'member-ban': 'Miembro baneado',
    reaction: 'Reacción',
    command: 'Comando',
    description: 'Descripción',
    'reaction-placeholder': 'ID de emoji o nombre o 😊',
    'specific-message-only': 'Mensaje específico solo',
    'message-id': 'ID de mensaje',
    phrase: 'Frase',
    'requires-role': 'Requiere rol',
    'required-role': 'Rol requerido',
    'role-id': 'ID de rol',
    'requires-admin': 'Requiere admin',
    'send-message': 'Enviar mensaje',
    'channel-message': 'Mensaje de canal',
    'send-channel-embed': 'Enviar embed de canal',
    'channel-embed-title': 'Título del embed de canal',
    'channel-embed-description': 'Descripción del embed de canal',
    'channel-embed-footer': 'Pie de página del embed de canal',
    'channel-embed-image': 'Imagen del embed de canal',
    'channel-embed-thumbnail': 'Miniatura del embed de canal',
    'channel-embed-color': 'Color del embed de canal',
    'is-specific-channel': 'Es canal específico',
    'specific-channel': 'Canal específico',
    'send-private-message': 'Enviar mensaje privado',
    'private-message': 'Mensaje privado',
    'send-private-embed': 'Enviar embed privado',
    'private-embed-title': 'Título del embed privado',
    'private-embed-description': 'Descripción del embed privado',
    'private-embed-footer': 'Pie de página del embed privado',
    'private-embed-image': 'Imagen del embed privado',
    'private-embed-thumbnail': 'Miniatura del embed privado',
    'private-embed-color': 'Color del embed privado',
    'react-to-message': 'React to Message',
    'ignore-error-message': 'Ignorar mensaje de error',
    'delete-if-contains': 'Eliminar si contiene',
    'delete-if-strings': 'Eliminar si cadenas',
    'delete-after': 'Eliminar después',
    'delete-x-times': 'Eliminar X veces',
    'delete-num': 'Eliminar número',
    'is-nsfw': 'Es NSFW',
    moderation: 'Moderación',
    kick: 'Expulsar',
    ban: 'Banear',
    'voice-mute': 'Silenciar voz',
    'role-assigner': 'Asignar rol',
    'role-to-assign': 'Rol a asignar',
    'update-command': 'Actualizar comando',
    action: 'Acción',
    hours: 'h',
    minutes: 'm',
    seconds: 's',
    'status-online': 'En línea',
    'status-idle': 'Ocioso',
    'status-dnd': 'No Disturbiar',
    'status-invisible': 'Invisible',
    'activity-playing': 'Jugando',
    'activity-streaming': 'Transmitiendo',
    'activity-listening': 'Escuchando',
    'activity-watching': 'Viendo',
    'activity-none': 'Ninguno',
    'activity-competing': 'Competiendo',
    'language-tooltip': 'El idioma puede ser una traducción automática.',
    'no-state-data': 'No hay datos de estado.',
    help: 'Ayuda',
    details: 'Detalles',
    actions: 'Acciones',
    'command-trigger': 'Disparador de comando',
    'command-only': 'Solo comando',
    'starts-with': 'Comienza con',
    'startup-js': 'JavaScript de inicio',
    save: 'Guardar',
    'restart-js-engine': 'Reiniciar motor JS',
    export: 'Exportar',
    import: 'Importar',
    general: 'General',
    openai: 'OpenAI',
    'openai-api-key': 'Clave de API de OpenAI',
    'enter-your-openai-api-key': 'Introduce tu clave de API de OpenAI...',
    'openai-model': 'Modelo OpenAI',
    'developer-prompt': 'Prompt del Desarrollador',
    'enter-your-custom-developer-prompt': 'Introduce tu prompt de desarrollador personalizado...',
    advanced: 'Avanzado',
    'use-legacy-interpreter': 'Usar Intérprete Antiguo',
    // AI Chat strings
    'ai-assistant': 'Asistente IA',
    'ai-chat-started': 'Asistente IA listo para editar comando:',
    'proposed-changes': 'Cambios Propuestos',
    changes: 'cambios',
    'accept-changes': 'Aceptar Cambios',
    reject: 'Rechazar',
    'changes-applied': 'Cambios aplicados exitosamente',
    'changes-rejected': 'Cambios rechazados',
    'describe-changes': 'Describe lo que quieres cambiar...',
    'api-key-needed': 'Se requiere clave API de OpenAI',
    'openai-key-required':
      'Por favor agrega tu clave API de OpenAI en Configuración para usar el asistente IA.',
    'select-model': 'Seleccionar Modelo IA',
    'total-tokens': 'Tokens totales usados',
    'new-chat': 'Nueva Conversación',
    close: 'Cerrar',
    'make-funnier': 'Hacer más divertido',
    'add-randomness': 'Agregar aleatoriedad',
    'use-mentions': 'Usar menciones',
    'add-counter': 'Agregar contador',
    'quick-make-funnier': 'Hacer esta respuesta de comando más divertida y atractiva',
    'quick-add-random': 'Agregar variaciones aleatorias a la respuesta usando $random{}',
    'quick-add-mentions': 'Incluir menciones de usuario como $name y $botName en la respuesta',
    'quick-add-counter': 'Agregar un contador usando $eval y botState para rastrear uso del comando',
    // Validation messages
    'fix-errors-to-save': 'Corregir errores para guardar',
    'description-required': 'La descripción es obligatoria',
    'command-required': 'El comando es obligatorio',
    'message-is-required': 'El mensaje es obligatorio',
    'embed-field-required': 'Se requiere al menos un campo de embed',
    'channel-id-required': 'Se requiere el ID del canal',
    'reaction-required': 'Se requiere la reacción',
    'delete-strings-required': 'Se requieren las cadenas de eliminación',
    'delete-number-required': 'El número de eliminación debe ser al menos 1',
    'role-id-is-required': 'Se requiere el ID del rol',
    'no-actions-added-hint': 'No hay acciones añadidas. Añade al menos una acción.',
    'send-channel-message': 'Enviar mensaje de canal'
    // ... more Spanish strings
  },
  ja: {
    'send-webhook': 'Discord Webhookを送信',
    'webhook-url': 'Webhook URL',
    name: '名前',
    avatar: 'アバターURL',
    message: 'メッセージ',
    send: '送信',
    bot: 'ボット',
    'message-placeholder': 'ここにメッセージを入力してください',
    token: 'トークン',
    login: 'ログイン',
    logout: 'ログアウト',
    invite: '招待',
    status: 'ステータス',
    activity: 'アクティビティ',
    'status-details': 'ステータスの詳細',
    'status-details-placeholder': 'ここにステータスの詳細を入力してください',
    'twitch-url': 'Twitch.tv URL',
    'update-status': 'ステータスを更新',
    settings: '設定',
    theme: 'テーマ',
    'show-token': 'トークンを表示',
    language: '言語',
    about: '約',
    'bot-state': 'ボットの状態',
    value: '値',
    'run-code': 'コードを実行',
    'run-code-placeholder': 'ここにJavaScriptコードを入力してください...',
    output: '出力',
    run: '実行',
    stats: '統計',
    users: 'ユーザー',
    'messages-sent': '送信されたメッセージ',
    'messages-received': '受信したメッセージ',
    'on-join': '参加時',
    'on-leave': '退会時',
    'on-ban': '禁止時',
    'private-messages-received': '受信したプライベートメッセージ',
    servers: 'サーバー',
    commands: 'コマンド',
    'time-spent-in-app': 'アプリでの時間',
    'webhooks-sent': '送信されたWebhook',
    cancel: 'キャンセル',
    'add-command': 'コマンドを追加',
    'no-commands-found': 'コマンドが見つかりません。',
    'command-exported-to-clipboard': 'コマンドがクリップボードにエクスポートされました！',
    delete: '削除',
    'are-you-sure-you-want-to-delete-the-command': 'コマンドを削除してもよろしいですか？',
    'open-quote': '「',
    'close-quote': '」',
    'edit-command': 'コマンドを編集',
    'choose-command-type': 'コマンドタイプを選択',
    'message-received': 'メッセージを受信',
    'private-message-received': 'プライベートメッセージを受信',
    'member-join': 'メンバー参加',
    'member-leave': 'メンバー退会',
    'member-ban': 'メンバー禁止',
    reaction: 'リアクション',
    command: 'コマンド',
    description: '説明',
    'reaction-placeholder': '絵文字IDまたは名前または😊',
    'specific-message-only': '特定のメッセージのみ',
    'message-id': 'メッセージID',
    phrase: 'フレーズ',
    'requires-role': '役割が必要',
    'required-role': '必要な役割',
    'role-id': '役割ID',
    'requires-admin': '管理者が必要',
    'send-message': 'メッセージを送信',
    'channel-message': 'チャンネルメッセージ',
    'send-channel-embed': 'チャンネル埋め込みを送信',
    'channel-embed-title': 'チャンネル埋め込みタイトル',
    'channel-embed-description': 'チャンネル埋め込み説明',
    'channel-embed-footer': 'チャンネル埋め込みフッター',
    'channel-embed-image': 'チャンネル埋め込み画像',
    'channel-embed-thumbnail': 'チャンネル埋め込みサムネイル',
    'channel-embed-color': 'チャンネル埋め込み色',
    'is-specific-channel': '特定のチャンネルです',
    'specific-channel': '特定のチャンネル',
    'send-private-message': 'プライベートメッセージを送信',
    'private-message': 'プライベートメッセージ',
    'send-private-embed': 'プライベート埋め込みを送信',
    'private-embed-title': 'プライベート埋め込みタイトル',
    'private-embed-description': 'プライベート埋め込み説明',
    'private-embed-footer': 'プライベート埋め込みフッター',
    'private-embed-image': 'プライベート埋め込み画像',
    'private-embed-thumbnail': 'プライベート埋め込みサムネイル',
    'private-embed-color': 'プライベート埋め込み色',
    'react-to-message': 'メッセージに反応',
    'ignore-error-message': 'エラーメッセージを無視',
    'delete-if-contains': '含まれている場合は削除',
    'delete-if-strings': '文字列の場合は削除',
    'delete-after': '後に削除',
    'delete-x-times': 'X回削除',
    'delete-num': '削除数',
    'is-nsfw': 'NSFWです',
    moderation: 'モデレーション',
    kick: 'キック',
    ban: '禁止',
    'voice-mute': 'ボイスミュート',
    'role-assigner': '役割を割り当てる',
    'role-to-assign': '割り当てる役割',
    'update-command': 'コマンドを更新',
    action: 'アクション',
    hours: '時間',
    minutes: '分',
    seconds: '秒',
    'status-online': 'オンライン',
    'status-idle': 'アイドル',
    'status-dnd': 'ドントディストラクト',
    'status-invisible': 'インビジブル',
    'activity-playing': 'プレイング',
    'activity-streaming': 'ストリーミング',
    'activity-listening': 'リスニング',
    'activity-watching': 'ウォッチング',
    'activity-none': 'ノーン',
    'activity-competing': 'コンペティング',
    'language-tooltip': '言語は自動翻訳される可能性があります。',
    'no-state-data': '状態データがありません。',
    help: 'ヘルプ',
    details: '詳細',
    actions: 'アクション',
    'command-trigger': 'コマンドトリガー',
    'command-only': 'コマンドのみ',
    'starts-with': 'で始まる',
    'startup-js': '起動JavaScript',
    save: '保存',
    'restart-js-engine': 'JSエンジンを再起動',
    export: 'エクスポート',
    import: 'インポート',
    general: '一般',
    openai: 'OpenAI',
    'openai-api-key': 'OpenAI APIキー',
    'enter-your-openai-api-key': 'OpenAI APIキーを入力してください...',
    'openai-model': 'OpenAIモデル',
    'developer-prompt': '開発者プロンプト',
    'enter-your-custom-developer-prompt': 'カスタム開発者プロンプトを入力してください...',
    advanced: '詳細設定',
    'use-legacy-interpreter': '旧インタープリターを使用',
    // AI Chat strings
    'ai-assistant': 'AIアシスタント',
    'ai-chat-started': 'AIアシスタントがコマンド編集の準備ができました:',
    'proposed-changes': '提案された変更',
    changes: '変更',
    'accept-changes': '変更を承認',
    reject: '拒否',
    'changes-applied': '変更が正常に適用されました',
    'changes-rejected': '変更が拒否されました',
    'describe-changes': '変更したい内容を説明してください...',
    'api-key-needed': 'OpenAI APIキーが必要です',
    'openai-key-required': 'AIアシスタントを使用するには、設定でOpenAI APIキーを追加してください。',
    'select-model': 'AIモデルを選択',
    'total-tokens': '合計トークン使用量',
    'new-chat': '新しいチャット',
    close: '閉じる',
    'make-funnier': 'もっと面白く',
    'add-randomness': 'ランダム性を追加',
    'use-mentions': 'メンションを使用',
    'add-counter': 'カウンターを追加',
    'quick-make-funnier': 'このコマンドの応答をより面白く魅力的にする',
    'quick-add-random': '$random{}を使用して応答にランダムなバリエーションを追加',
    'quick-add-mentions': '$nameや$botNameなどのユーザーメンションを応答に含める',
    'quick-add-counter': '$evalとbotStateを使用してコマンド使用回数を追跡するカウンターを追加'
    // ... more Japanese strings
  },
  zh: {
    'send-webhook': '发送Discord Webhook',
    'webhook-url': 'Webhook URL',
    name: '名称',
    avatar: '头像URL',
    message: '消息',
    send: '发送',
    bot: '机器人',
    'message-placeholder': '在此输入消息',
    token: '令牌',
    login: '登录',
    logout: '登出',
    invite: '邀请',
    status: '状态',
    activity: '活动',
    'status-details': '状态详情',
    'status-details-placeholder': '在此输入状态详情',
    'twitch-url': 'Twitch.tv URL',
    'update-status': '更新状态',
    settings: '设置',
    theme: '主题',
    'show-token': '显示令牌',
    language: '语言',
    about: '关于',
    'bot-state': '机器人状态',
    value: '值',
    'run-code': '运行代码',
    'run-code-placeholder': '在此输入JavaScript代码...',
    output: '输出',
    run: '运行',
    stats: '统计',
    users: '用户',
    'messages-sent': '已发送消息',
    'messages-received': '已接收消息',
    'on-join': '加入时',
    'on-leave': '离开时',
    'on-ban': '被禁时',
    'private-messages-received': '接收的私人消息',
    servers: '服务器',
    commands: '命令',
    'time-spent-in-app': '在应用中花费的时间',
    'webhooks-sent': '已发送的Webhook',
    cancel: '取消',
    'add-command': '添加命令',
    'no-commands-found': '未找到命令。',
    'command-exported-to-clipboard': '命令已导出到剪贴板！',
    delete: '删除',
    'are-you-sure-you-want-to-delete-the-command': '您确定要删除命令吗？',
    'open-quote': '“',
    'close-quote': '”',
    'edit-command': '编辑命令',
    'choose-command-type': '选择命令类型',
    'message-received': '收到消息',
    'private-message-received': '收到私人消息',
    'member-join': '成员加入',
    'member-leave': '成员离开',
    'member-ban': '成员被禁',
    reaction: '反应',
    command: '命令',
    description: '描述',
    'reaction-placeholder': '表情符号ID或名称或😊',
    'specific-message-only': '仅特定消息',
    'message-id': '消息ID',
    phrase: '短语',
    'requires-role': '需要角色',
    'required-role': '所需角色',
    'role-id': '角色ID',
    'requires-admin': '需要管理员',
    'send-message': '发送消息',
    'channel-message': '频道消息',
    'send-channel-embed': '发送频道嵌入',
    'channel-embed-title': '频道嵌入标题',
    'channel-embed-description': '频道嵌入描述',
    'channel-embed-footer': '频道嵌入页脚',
    'channel-embed-image': '频道嵌入图片',
    'channel-embed-thumbnail': '频道嵌入缩略图',
    'channel-embed-color': '频道嵌入颜色',
    'is-specific-channel': '是特定频道',
    'specific-channel': '特定频道',
    'send-private-message': '发送私人消息',
    'private-message': '私人消息',
    'send-private-embed': '发送私人嵌入',
    'private-embed-title': '私人嵌入标题',
    'private-embed-description': '私人嵌入描述',
    'private-embed-footer': '私人嵌入页脚',
    'private-embed-image': '私人嵌入图片',
    'private-embed-thumbnail': '私人嵌入缩略图',
    'private-embed-color': '私人嵌入颜色',
    'react-to-message': '对消息做出反应',
    'ignore-error-message': '忽略错误消息',
    'delete-if-contains': '如果包含则删除',
    'delete-if-strings': '如果是字符串则删除',
    'delete-after': '之后删除',
    'delete-x-times': '删除X次',
    'delete-num': '删除数量',
    'is-nsfw': '是NSFW',
    moderation: '管理',
    kick: '踢出',
    ban: '禁止',
    'voice-mute': '语音静音',
    'role-assigner': '角色分配器',
    'role-to-assign': '要分配的角色',
    'update-command': '更新命令',
    action: '动作',
    hours: '小时',
    minutes: '分钟',
    seconds: '秒',
    'status-online': '在线',
    'status-idle': '空闲',
    'status-dnd': '请勿打扰',
    'status-invisible': '隐身',
    'activity-playing': '玩',
    'activity-streaming': '直播',
    'activity-listening': '听',
    'activity-watching': '看',
    'activity-none': '无',
    'activity-competing': '竞争',
    'language-tooltip': '语言可能是机器翻译的。',
    'no-state-data': '没有状态数据。',
    help: '帮助',
    details: '详情',
    actions: '操作',
    'command-trigger': '命令触发器',
    'command-only': '仅命令',
    'starts-with': '以...开始',
    'startup-js': '启动JavaScript',
    save: '保存',
    'restart-js-engine': '重启JS引擎',
    export: '导出',
    import: '导入',
    general: '通用',
    openai: 'OpenAI',
    'openai-api-key': 'OpenAI API密钥',
    'enter-your-openai-api-key': '输入您的OpenAI API密钥...',
    'openai-model': 'OpenAI模型',
    'developer-prompt': '开发者提示',
    'enter-your-custom-developer-prompt': '输入您的自定义开发者提示...',
    advanced: '高级',
    'use-legacy-interpreter': '使用旧版解释器',
    // AI Chat strings
    'ai-assistant': 'AI助手',
    'ai-chat-started': 'AI助手已准备好帮助编辑命令:',
    'proposed-changes': '建议的更改',
    changes: '更改',
    'accept-changes': '接受更改',
    reject: '拒绝',
    'changes-applied': '更改已成功应用',
    'changes-rejected': '更改已拒绝',
    'describe-changes': '描述您想要更改的内容...',
    'api-key-needed': '需要OpenAI API密钥',
    'openai-key-required': '请在设置中添加您的OpenAI API密钥以使用AI助手。',
    'select-model': '选择AI模型',
    'total-tokens': '总Token使用量',
    'new-chat': '新对话',
    close: '关闭',
    'make-funnier': '更有趣',
    'add-randomness': '添加随机性',
    'use-mentions': '使用提及',
    'add-counter': '添加计数器',
    'quick-make-funnier': '使此命令响应更有趣和吸引人',
    'quick-add-random': '使用$random{}为响应添加随机变化',
    'quick-add-mentions': '在响应中包含用户提及，如$name和$botName',
    'quick-add-counter': '使用$eval和botState添加计数器来跟踪命令使用情况'
    // ... more Simplified Chinese strings
  },
  ko: {
    'send-webhook': 'Discord Webhook 보내기',
    'webhook-url': 'Webhook URL',
    name: '이름',
    avatar: '아바타 URL',
    message: '메시지',
    send: '보내기',
    bot: '봇',
    'message-placeholder': '여기에 메시지를 입력하세요',
    token: '토큰',
    login: '로그인',
    logout: '로그아웃',
    invite: '초대',
    status: '상태',
    activity: '활동',
    'status-details': '상태 세부 정보',
    'status-details-placeholder': '여기에 상태 세부 정보를 입력하세요',
    'twitch-url': 'Twitch.tv URL',
    'update-status': '상태 업데이트',
    settings: '설정',
    theme: '테마',
    'show-token': '토큰 표시',
    language: '언어',
    about: '정보',
    'bot-state': '봇 상태',
    value: '값',
    'run-code': '코드 실행',
    'run-code-placeholder': '여기에 JavaScript 코드를 입력하세요...',
    output: '출력',
    run: '실행',
    stats: '통계',
    users: '사용자',
    'messages-sent': '보낸 메시지',
    'messages-received': '받은 메시지',
    'on-join': '참여 시',
    'on-leave': '떠날 때',
    'on-ban': '차단 시',
    'private-messages-received': '받은 개인 메시지',
    servers: '서버',
    commands: '명령어',
    'time-spent-in-app': '앱에서 보낸 시간',
    'webhooks-sent': '보낸 Webhook',
    cancel: '취소',
    'add-command': '명령어 추가',
    'no-commands-found': '명령어를 찾을 수 없습니다.',
    'command-exported-to-clipboard': '명령어가 클립보드에 내보내졌습니다!',
    delete: '삭제',
    'are-you-sure-you-want-to-delete-the-command': '명령어를 삭제하시겠습니까?',
    'open-quote': '“',
    'close-quote': '”',
    'edit-command': '명령어 편집',
    'choose-command-type': '명령어 유형 선택',
    'message-received': '메시지 수신',
    'private-message-received': '개인 메시지 수신',
    'member-join': '회원 가입',
    'member-leave': '회원 탈퇴',
    'member-ban': '회원 차단',
    reaction: '반응',
    command: '명령어',
    description: '설명',
    'reaction-placeholder': '이모지 ID 또는 이름 또는 😊',
    'specific-message-only': '특정 메시지만',
    'message-id': '메시지 ID',
    phrase: '구문',
    'requires-role': '역할 필요',
    'required-role': '필요한 역할',
    'role-id': '역할 ID',
    'requires-admin': '관리자 필요',
    'send-message': '메시지 보내기',
    'channel-message': '채널 메시지',
    'send-channel-embed': '채널 임베드 보내기',
    'channel-embed-title': '채널 임베드 제목',
    'channel-embed-description': '채널 임베드 설명',
    'channel-embed-footer': '채널 임베드 바닥글',
    'channel-embed-image': '채널 임베드 이미지',
    'channel-embed-thumbnail': '채널 임베드 썸네일',
    'channel-embed-color': '채널 임베드 색상',
    'is-specific-channel': '특정 채널입니다',
    'specific-channel': '특정 채널',
    'send-private-message': '개인 메시지 보내기',
    'private-message': '개인 메시지',
    'send-private-embed': '개인 임베드 보내기',
    'private-embed-title': '개인 임베드 제목',
    'private-embed-description': '개인 임베드 설명',
    'private-embed-footer': '개인 임베드 바닥글',
    'private-embed-image': '개인 임베드 이미지',
    'private-embed-thumbnail': '개인 임베드 썸네일',
    'private-embed-color': '개인 임베드 색상',
    'react-to-message': '메시지에 반응',
    'ignore-error-message': '오류 메시지 무시',
    'delete-if-contains': '포함 시 삭제',
    'delete-if-strings': '문자열 시 삭제',
    'delete-after': '후에 삭제',
    'delete-x-times': 'X번 삭제',
    'delete-num': '삭제 수',
    'is-nsfw': 'NSFW입니다',
    moderation: '관리',
    kick: '추방',
    ban: '차단',
    'voice-mute': '음성 음소거',
    'role-assigner': '역할 할당자',
    'role-to-assign': '할당할 역할',
    'update-command': '명령어 업데이트',
    action: '동작',
    hours: '시간',
    minutes: '분',
    seconds: '초',
    'status-online': '온라인',
    'status-idle': '아이들',
    'status-dnd': '노키즈 디스트럭트',
    'status-invisible': '인비저블',
    'activity-playing': '플레이',
    'activity-streaming': '스트리밍',
    'activity-listening': '리스닝',
    'activity-watching': '워치',
    'activity-none': '노',
    'activity-competing': '경쟁',
    'language-tooltip': '언어는 자동 번역일 수 있습니다.',
    'no-state-data': '상태 데이터가 없습니다.',
    help: '도움말',
    details: '세부 정보',
    actions: '작업',
    'command-trigger': '명령 트리거',
    'command-only': '명령만',
    'starts-with': '시작',
    'startup-js': '시작 JavaScript',
    save: '저장',
    'restart-js-engine': 'JS 엔진 재시작',
    export: '내보내기',
    import: '가져오기',
    general: '일반',
    openai: 'OpenAI',
    'openai-api-key': 'OpenAI API 키',
    'enter-your-openai-api-key': 'OpenAI API 키를 입력하세요...',
    'openai-model': 'OpenAI 모델',
    'developer-prompt': '개발자 프롬프트',
    'enter-your-custom-developer-prompt': '사용자 정의 개발자 프롬프트를 입력하세요...',
    advanced: '고급',
    'use-legacy-interpreter': '레거시 인터프리터 사용',
    // AI Chat strings
    'ai-assistant': 'AI 어시스턴트',
    'ai-chat-started': 'AI 어시스턴트가 명령 편집 준비 완료:',
    'proposed-changes': '제안된 변경 사항',
    changes: '변경',
    'accept-changes': '변경 수락',
    reject: '거부',
    'changes-applied': '변경 사항이 성공적으로 적용되었습니다',
    'changes-rejected': '변경 사항이 거부되었습니다',
    'describe-changes': '변경하고 싶은 내용을 설명하세요...',
    'api-key-needed': 'OpenAI API 키가 필요합니다',
    'openai-key-required': 'AI 어시스턴트를 사용하려면 설정에서 OpenAI API 키를 추가하세요.',
    'select-model': 'AI 모델 선택',
    'total-tokens': '총 토큰 사용량',
    'new-chat': '새 채팅',
    close: '닫기',
    'make-funnier': '더 재미있게',
    'add-randomness': '무작위성 추가',
    'use-mentions': '멘션 사용',
    'add-counter': '카운터 추가',
    'quick-make-funnier': '이 명령 응답을 더 재미있고 매력적으로 만들기',
    'quick-add-random': '$random{}을 사용하여 응답에 무작위 변형 추가',
    'quick-add-mentions': '$name 및 $botName과 같은 사용자 멘션을 응답에 포함',
    'quick-add-counter': '$eval 및 botState를 사용하여 명령 사용량을 추적하는 카운터 추가'
    // ... more Korean strings
  },
  ru: {
    'send-webhook': 'Отправить Discord Webhook',
    'webhook-url': 'URL вебхука',
    name: 'Имя',
    avatar: 'URL аватара',
    message: 'Сообщение',
    send: 'Отправить',
    bot: 'Бот',
    'message-placeholder': 'Введите ваше сообщение здесь',
    token: 'Токен',
    login: 'Войти',
    logout: 'Выйти',
    invite: 'Пригласить',
    status: 'Статус',
    activity: 'Активность',
    'status-details': 'Детали статуса',
    'status-details-placeholder': 'Введите детали вашего статуса здесь',
    'twitch-url': 'URL Twitch.tv',
    'update-status': 'Обновить статус',
    settings: 'Настройки',
    theme: 'Тема',
    'show-token': 'Показать токен',
    language: 'Язык',
    about: 'О программе',
    'bot-state': 'Состояние бота',
    value: 'Значение',
    'run-code': 'Запустить код',
    'run-code-placeholder': 'Введите JavaScript код здесь...',
    output: 'Вывод',
    run: 'Запустить',
    stats: 'Статистика',
    users: 'Пользователи',
    'messages-sent': 'Отправлено сообщений',
    'messages-received': 'Получено сообщений',
    'on-join': 'При присоединении',
    'on-leave': 'При выходе',
    'on-ban': 'При бане',
    'private-messages-received': 'Получено личных сообщений',
    servers: 'Серверы',
    commands: 'Команды',
    'time-spent-in-app': 'Время в приложении',
    'webhooks-sent': 'Отправлено вебхуков',
    cancel: 'Отмена',
    'add-command': 'Добавить команду',
    'no-commands-found': 'Команды не найдены.',
    'command-exported-to-clipboard': 'Команда экспортирована в буфер обмена!',
    delete: 'Удалить',
    'are-you-sure-you-want-to-delete-the-command': 'Вы уверены, что хотите удалить команду?',
    'open-quote': '«',
    'close-quote': '»',
    'edit-command': 'Редактировать команду',
    'choose-command-type': 'Выберите тип команды',
    'message-received': 'Сообщение получено',
    'private-message-received': 'Личное сообщение получено',
    'member-join': 'Участник присоединился',
    'member-leave': 'Участник покинул',
    'member-ban': 'Участник забанен',
    reaction: 'Реакция',
    command: 'Команда',
    description: 'Описание',
    'reaction-placeholder': 'ID или имя эмодзи или 😊',
    'specific-message-only': 'Только конкретное сообщение',
    'message-id': 'ID сообщения',
    phrase: 'Фраза',
    'requires-role': 'Требуется роль',
    'required-role': 'Требуемая роль',
    'role-id': 'ID роли',
    'requires-admin': 'Требуется администратор',
    'send-message': 'Отправить сообщение',
    'channel-message': 'Сообщение канала',
    'send-channel-embed': 'Отправить встраивание канала',
    'channel-embed-title': 'Заголовок встраивания канала',
    'channel-embed-description': 'Описание встраивания канала',
    'channel-embed-footer': 'Нижний колонтитул встраивания канала',
    'channel-embed-image': 'Изображение встраивания канала',
    'channel-embed-thumbnail': 'Миниатюра встраивания канала',
    'channel-embed-color': 'Цвет встраивания канала',
    'is-specific-channel': 'Это конкретный канал',
    'specific-channel': 'Конкретный канал',
    'send-private-message': 'Отправить личное сообщение',
    'private-message': 'Личное сообщение',
    'send-private-embed': 'Отправить личное встраивание',
    'private-embed-title': 'Заголовок личного встраивания',
    'private-embed-description': 'Описание личного встраивания',
    'private-embed-footer': 'Нижний колонтитул личного встраивания',
    'private-embed-image': 'Изображение личного встраивания',
    'private-embed-thumbnail': 'Миниатюра личного встраивания',
    'private-embed-color': 'Цвет личного встраивания',
    'react-to-message': 'Реагировать на сообщение',
    'ignore-error-message': 'Игнорировать сообщение об ошибке',
    'delete-if-contains': 'Удалить, если содержит',
    'delete-if-strings': 'Удалить, если строки',
    'delete-after': 'Удалить после',
    'delete-x-times': 'Удалить X раз',
    'delete-num': 'Удалить количество',
    'is-nsfw': 'Это NSFW',
    moderation: 'Модерация',
    kick: 'Кик',
    ban: 'Бан',
    'voice-mute': 'Отключить голос',
    'role-assigner': 'Назначение роли',
    'role-to-assign': 'Роль для назначения',
    'update-command': 'Обновить команду',
    action: 'Действие',
    hours: 'ч',
    minutes: 'мин',
    seconds: 'с',
    'status-online': 'Онлайн',
    'status-idle': 'Игра',
    'status-dnd': 'Не беспокоить',
    'status-invisible': 'Невидимый',
    'activity-playing': 'Игра',
    'activity-streaming': 'Стрим',
    'activity-listening': 'Слушать',
    'activity-watching': 'Смотреть',
    'activity-none': 'Ничего',
    'activity-competing': 'Соревнование',
    'language-tooltip': 'Язык может быть машинным переводом.',
    'no-state-data': 'Нет данных о состоянии.',
    help: 'Помощь',
    details: 'Подробности',
    actions: 'Действия',
    'command-trigger': 'Триггер команды',
    'command-only': 'Только команда',
    'starts-with': 'Начинается с',
    'startup-js': 'Запуск JavaScript',
    save: 'Сохранить',
    'restart-js-engine': 'Перезапустить JS-движок',
    export: 'Экспорт',
    import: 'Импорт',
    general: 'Общие',
    openai: 'OpenAI',
    'openai-api-key': 'API-ключ OpenAI',
    'enter-your-openai-api-key': 'Введите ваш API-ключ OpenAI...',
    'openai-model': 'Модель OpenAI',
    'developer-prompt': 'Запрос разработчика',
    'enter-your-custom-developer-prompt': 'Введите свой пользовательский запрос разработчика...',
    advanced: 'Дополнительно',
    'use-legacy-interpreter': 'Использовать старый интерпретатор',
    // AI Chat strings
    'ai-assistant': 'ИИ Ассистент',
    'ai-chat-started': 'ИИ ассистент готов помочь отредактировать команду:',
    'proposed-changes': 'Предлагаемые изменения',
    changes: 'изменения',
    'accept-changes': 'Принять изменения',
    reject: 'Отклонить',
    'changes-applied': 'Изменения успешно применены',
    'changes-rejected': 'Изменения отклонены',
    'describe-changes': 'Опишите, что вы хотите изменить...',
    'api-key-needed': 'Требуется API-ключ OpenAI',
    'openai-key-required':
      'Пожалуйста, добавьте ваш API-ключ OpenAI в настройках для использования ИИ ассистента.',
    'select-model': 'Выберите модель ИИ',
    'total-tokens': 'Всего использовано токенов',
    'new-chat': 'Новый чат',
    close: 'Закрыть',
    'make-funnier': 'Сделать смешнее',
    'add-randomness': 'Добавить случайность',
    'use-mentions': 'Использовать упоминания',
    'add-counter': 'Добавить счётчик',
    'quick-make-funnier': 'Сделать этот ответ команды смешнее и увлекательнее',
    'quick-add-random': 'Добавить случайные вариации в ответ с помощью $random{}',
    'quick-add-mentions': 'Включить упоминания пользователей, такие как $name и $botName, в ответ',
    'quick-add-counter':
      'Добавить счётчик с использованием $eval и botState для отслеживания использования команды'
    // ... more Russian strings
  }
  // ... more languages
}

// Create a writable store for the current language
export const currentLanguage = writable(DEFAULT_LANGUAGE)

// Create a derived store for the translation function
export const t = derived(currentLanguage, ($currentLanguage) => (key: string) => {
  // Try to get the string in the current language
  const translation = translations[$currentLanguage]?.[key]
  if (translation) return translation

  // Fallback to English if the string doesn't exist in the current language
  const fallback = translations[DEFAULT_LANGUAGE]?.[key]
  if (fallback) return fallback

  // Return the key itself if no translation is found
  console.warn(`Missing translation for key: "${key}" in language: "${$currentLanguage}"`)
  return key
})

// Function to change the current language
export const setLanguage = (language: string) => {
  if (translations[language]) {
    currentLanguage.set(language)
  }
}
